### ISSUE TITLE
[Widget] 살래 말래 Card 

### ISSUE THREAD

**Issue by korca0220** [Fun-d-6th-Stock-King/should-have-bought-app#8]
# ToDo
- [ ] 살래? 말래? 카드 위젯 개발
- [ ] Semi-Develop

# 참고 링크
- https://www.figma.com/file/GWb3LF6jL1W6FFAOFqdgIt/%EA%B7%B8%EB%95%8C%EC%82%B4%EA%B1%B8?node-id=214%3A2987

**Comment by Soobinnn** [comment]
완료
